// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/prompts": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/prompts" | "/settings";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/prompts.tsx": {
    id: "routes/prompts";
    page: "/prompts";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/prompts": typeof import("./src/routes/prompts.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
};