// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/history" | "/settings";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/history": typeof import("./src/routes/history.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
};